#!/bin/sh

mkdir /proc
mount -t proc proc /proc

# TODO: Is it really working?
mount -t sysfs none /sys

insmod /bin/benchmark_module.ko

cat <<!

Boot took $(cut -d' ' -f1 /proc/uptime) seconds

Hello from Linux!

!

exec /bin/sh
