name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: sudo apt-get update && sudo apt-get install gcc-riscv64-linux-gnu libgnutls28-dev bc binutils bison dwarves flex git gnupg2 gzip libelf-dev libncurses5-dev libssl-dev make openssl pahole perl-base rsync tar xz-utils
      - name: Build
        run: make
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            opensbi.bin
            opensbi.elf
            opensbi_jump.bin
            opensbi_jump.elf
            opensbi-linux-kernel-exit.bin
            opensbi-linux-kernel-exit.elf
            opensbi-linux-kernel-shell.bin
            opensbi-linux-kernel-shell.elf
            opensbi-linux-kernel-driver.bin
            opensbi-linux-kernel-driver.elf
            opensbi-linux-kernel-lock.bin
            opensbi-linux-kernel-lock.elf
            u-boot.bin
            u-boot.elf
            u-boot-exit.bin
            u-boot-exit.elf
